=== ADClubes/KalaClub/Modificaciones/0912/CT_ORIGEN_VENTA.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="CT_ORIGEN_VENTA" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="CT_ORIGEN_VENTA">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="idOrigenVenta " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="idOrigenVenta" index-key="idOrigenVenta " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="idOrigenVenta" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="DescripcionOrigenVenta" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Grupo" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="15"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="EsVenta" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="1"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SinCosto" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="1"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="FechaInicial" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="FechaFinal" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== ADClubes/KalaClub/Modificaciones/0912/CT_ORIGEN_VENTA.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="CT_ORIGEN_VENTA.xsd" generated="2009-12-29T17:24:31">
<CT_ORIGEN_VENTA>
<idOrigenVenta>1</idOrigenVenta>
<DescripcionOrigenVenta>VENTA</DescripcionOrigenVenta>
<Grupo>VENTA</Grupo>
<EsVenta>S</EsVenta>
<SinCosto>N</SinCosto>
<FechaInicial>2009-12-01T00:00:00</FechaInicial>
<FechaFinal>2010-12-31T00:00:00</FechaFinal>
</CT_ORIGEN_VENTA>
<CT_ORIGEN_VENTA>
<idOrigenVenta>2</idOrigenVenta>
<DescripcionOrigenVenta>TRASPASO</DescripcionOrigenVenta>
<Grupo>TRASPASO</Grupo>
<EsVenta>N</EsVenta>
<SinCosto>S</SinCosto>
<FechaInicial>2009-12-01T00:00:00</FechaInicial>
<FechaFinal>2010-12-31T00:00:00</FechaFinal>
</CT_ORIGEN_VENTA>
<CT_ORIGEN_VENTA>
<idOrigenVenta>3</idOrigenVenta>
<DescripcionOrigenVenta>CORTESIA</DescripcionOrigenVenta>
<Grupo>CORTESIA</Grupo>
<EsVenta>N</EsVenta>
<SinCosto>S</SinCosto>
<FechaInicial>2009-12-01T00:00:00</FechaInicial>
<FechaFinal>2010-12-31T00:00:00</FechaFinal>
</CT_ORIGEN_VENTA>
<CT_ORIGEN_VENTA>
<idOrigenVenta>4</idOrigenVenta>
<DescripcionOrigenVenta>INTERCAMBIO</DescripcionOrigenVenta>
<Grupo>INTERCAMBIO</Grupo>
<EsVenta>N</EsVenta>
<SinCosto>S</SinCosto>
<FechaInicial>2009-12-01T00:00:00</FechaInicial>
<FechaFinal>2010-12-31T00:00:00</FechaFinal>
</CT_ORIGEN_VENTA>
<CT_ORIGEN_VENTA>
<idOrigenVenta>5</idOrigenVenta>
<DescripcionOrigenVenta>STAFF</DescripcionOrigenVenta>
<Grupo>STAFF</Grupo>
<EsVenta>N</EsVenta>
<SinCosto>S</SinCosto>
<FechaInicial>2009-12-01T00:00:00</FechaInicial>
<FechaFinal>2010-12-31T00:00:00</FechaFinal>
</CT_ORIGEN_VENTA>
<CT_ORIGEN_VENTA>
<idOrigenVenta>6</idOrigenVenta>
<DescripcionOrigenVenta>SISTEMA</DescripcionOrigenVenta>
<Grupo>SISTEMA</Grupo>
<EsVenta>N</EsVenta>
<SinCosto>S</SinCosto>
<FechaInicial>2009-12-01T00:00:00</FechaInicial>
<FechaFinal>2010-12-31T00:00:00</FechaFinal>
</CT_ORIGEN_VENTA>
</dataroot>
